name: ev_charger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  google_maps_flutter: ^2.6.0
  url_launcher: ^6.3.0
  mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/start_charging.jpg
    - assets/return_plug.jpg
    - assets/finish_charging.png

flutter_native_splash:
  color: "#FFFFFF"             # Background color
  image: assets/logo.jpg       # Path to your logo image
  android_12:
    image: assets/logo.jpg
    color: "#FFFFFF"

